name: Deploy to GitHub Pages

on:
  push:
    branches: ['main']
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Basic JS syntax check
        run: |
          node -e "new Function(require('fs').readFileSync('script.js','utf8'))"

      - name: HTML validation (tidy)
        run: |
          sudo apt-get update
          sudo apt-get install -y tidy
          check() {
            ec=0
            tidy -q -e "$1" || ec=$?
            if [ "$ec" -eq 2 ]; then
              echo "::error file=$1::HTML errors found"
              exit 2
            fi
            return 0
          }
          check index.html
          check svg-to-bmp.html

      - name: Broken links (README + HTML)
        uses: lycheeverse/lychee-action@v2
        with:
          args: --no-progress --exclude-mail --verbose "./README.md" "./**/*.html"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    needs: test
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5

      - name: Create .nojekyll file
        run: touch .nojekyll

      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "."

      - name: Deploy site to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4


